name = "esp32c3"
description = "ESP32-C3 SDK"
version = "0.0.0"

authors = ["Johannes Kliemann"]
maintainers = ["Johannes Kliemann <jk@jkliemann.de>"]
maintainers-logins = ["jklmnn"]

[[depends-on]]
gnat_riscv64_elf = "^11.2.4"

[[actions]]
type = "post-fetch"
command = ["tools/install_sdk.sh"]

[[actions]]
type = "post-build"
command = ["tools/build_sdk.sh"]
[[depends-on]]
esp32c3_lib = "~0.1.0-dev"
[[pins]]
esp32c3_lib = { url='https://github.com/jklmnn/esp32c3-ada-bindings.git' }
