name = "esp32c3"
description = "ESP32-C3 SDK"
version = "0.0.0"

authors = ["Johannes Kliemann"]
maintainers = ["Johannes Kliemann <jk@jkliemann.de>"]
maintainers-logins = ["jklmnn"]

[[depends-on]]
gnat_riscv64_elf = "^11.2.4"

[[actions]]
type = "post-fetch"
command = ["tools/install_sdk.sh"]

[[actions]]
type = "post-build"
command = ["tools/build_sdk.sh"]
[[depends-on]]
esp_idf = "~0.1.1"

[[pins]]
esp_idf = { path = "../esp-idf-ada-bindings" }
