name = "esp32c3"
description = "Shiny new project"
version = "0.0.0"

authors = ["Johannes Kliemann"]
maintainers = ["Johannes Kliemann <jk@jkliemann.de>"]
maintainers-logins = ["jklmnn"]

[[depends-on]]
gnat_riscv64_elf = "*"
